### PR TITLE
Display full tweet contents, even when there are more than 140 characters

### PR DESCRIPTION
**Pull request by MageFroh**
Use Extended Tweet mode to do so (https://developer.twitter.com/en/docs/tweets/tweet-updates).

Also includes a change that ignores files appearing in the cache directory.

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Thanks for the PR Benoit.  Glanced through the docs on the Twitter API site.  Do we need to update our docs to include `tweet_mode=extended` as a query in the URL to support this?  Can you confirm that you have this functioning across all included RSS and JSON generating PHP scripts?  I will need to look into how this might influence API rate limits c/w the previous approach that we used.  It looks like there may be new limits introduced since we last updated this.

**Comment by MageFroh** [comment]
Hi Chris,

With the change as it is today, `tweet_mode` is always added to the queries made to the twitter API.
There isn't any new query parameter for the callers of the PHP scripts.

I've checked that all the RSS PHP scripts still work fine.
I'm not sure the `tweet_mode` needs to be configurable for these scripts: truncating the tweets seemed like a bug when I first noticed it.

The JSON PHP scripts still work, but return the new format. Honestly, I didn't think much about it until now, but this is indeed a backward compatibility issue, since the `text` field has been renamed to `full_text`.
In order to keep backward compatibility, maybe we should indeed add a query option that changes the tweet_mode.
We could also make sure that the change is only impacting the RSS scripts.
What do you think is best?

Note that the Twitter page states:

> In the future, an additional announcement will be made when the time is right to make a change for the rendering mode to default to extended mode.

So the scripts should probably explicitly request the desired `tweet_mode` in all cases to protect against this future change.

**Comment by chrissimpkins** [comment]
Thanks @MageFroh.  I am not opposed to a major release increment to indicate the backwards incompatibility of this issue.  This was a major change in the Twitter API and this software should support it going forward.  I am not aware of any automated updating mechanisms in place that would lead to surprise on the user end. They would need to download new source files here and implement them according to updated docs for this new major version.

Is there a use case that you can come up with where truncated text would be prioritized over full text, even with an optional approach?  I don't know that I can come up with one.  Unless there is justification for it, I would favor transitioning to the new API for all future users of this project rather than trying to bridge the API changes that Twitter made.  

Shall I add this to a non-master branch for further work?  And if so, would you like to do any additional  work to make this release ready?  We will need to update documentation with the changes here.  Will definitely add you to the authors list for the PR changes contained here irrespective of whether you intend to do any further work.  It may just take a bit longer to get this out if it is left to me.

Thoughts?

**Comment by MageFroh** [comment]
Hi Chris,

I can't find a use case for the truncated API either.

Yes, feel free to put this on another branch to prepare the release, and I can help if you want.
Is it only about updating `README.md` with a backward compatibility warning and quick release description?

**Comment by chrissimpkins** [comment]
> feel free to put this on another branch to prepare the release

sounds good will do!

> Is it only about updating README.md with a backward compatibility warning and quick release description

I haven't visited the source / docs here in a couple of years.  I will need to dive into it when I have a bit of time to explore further.  Unclear at the moment.

**Comment by rodrigoaguilera** [comment]
Can you solve the conflicts?

I think we can take care of the rest when tagging a new release.

**Comment by rodrigoaguilera** [comment]
I rebased it myself and merged it. Thanks for the contribution

**Pull request closed without merging**
